// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"seckill/internal/dao/internal"
)

// goodsDao is the data access object for the table goods.
// You can define custom methods on it to extend its functionality as needed.
type goodsDao struct {
	*internal.GoodsDao
}

var (
	// Goods is a globally accessible object for table goods operations.
	Goods = goodsDao{internal.NewGoodsDao()}
)

// Add your custom methods and functionality below.
