// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package seckill

import (
	"seckill/api/seckill"
)

type ControllerV1 struct{}

func NewV1() seckill.ISeckillV1 {
	return &ControllerV1{}
}
